name: "release"

on:
  push:
    branches:
      - "next"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Test"
        run: |
          git clone https://github.com/VA-PLE/drupaleasystart.git
          cd drupaleasystart
          make

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: Drupal easy start
          files: |
            .env
            Makefile
            docker-compose.yml
