---
name: "release"

on:
  push:
    branches:
      - "next"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          git clone https://github.com/VA-PLE/drupaleasystart.git
#          cd drupaleasystart && pwd
          ls -la && pwd
          make info

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
#          automatic_release_tag: Release v1.0.9
          prerelease: false
          title: "Drupal easy start `date +%y.%m`"
          files: |
            LICENSE.txt
            *.jar
