name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        make upenv && cat .env
        git config --global user.email "bot@autoupdate.com"
        git config --global user.name "botautoupdate"
        git status
        git add .env        
        git commit -am "BOT update .env"
        git push origin next
