name: Bot auto-update

on:
  schedule:
    - cron:  '0 16 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Run a multi-line script
      run: |
        make upenv
        git config --global user.email "bot@autoupdate.com"
        git config --global user.name "botautoupdate"
        git add .env        
        git commit -am "BOT update .env"
        git push origin next
